### ISSUE TITLE
Make the autotools build of libmarpa-sys suck less

### ISSUE THREAD

**Issue by jrobsonchase** [Pursuit92/marpa#5]
I apparently broke things for everyone *not* using autotools 1.16 when I ran `autoreconf -i` so that I could run `cargo publish` from my computer. Might need to revert that change, but it still won't solve my problem of `cargo package` failing because it tries to reconfigure libmarpa during `make install` for some reason.

More exploration needed.

**Comment by jrobsonchase** [comment]
welp, both bdd4846cd722e81f6d0874a3f17dd78acd19adb2 and 6acf7ab463ea3e4264a485ddc307dd3748c89d72 fail, so I'm not sure what's up with autotools :confused: 

More reports of can/cannot build successfully would be welcome.

**Comment by dginev** [comment]
Here's what I am seeing on the `Revert "autoreconf -i"` commit that is the current latest:

```
$ RUST_BACKTRACE=1 cargo build
   Compiling libmarpa-sys v0.1.3 (/home/deyan/git/marpa/libmarpa-sys)
   Compiling libmarpa-sys v0.1.3
   Compiling marpa v0.2.3 (/home/deyan/git/marpa/marpa)
error: failed to run custom build command for `libmarpa-sys v0.1.3 (/home/deyan/git/marpa/libmarpa-sys)`
process didn't exit successfully: `/home/deyan/git/marpa/target/debug/build/libmarpa-sys-6dee1d379a55d870/build-script-build` (exit code: 101)
--- stdout
running: "/home/deyan/git/marpa/libmarpa-sys/libmarpa-8.3.0/configure" "--prefix=/home/deyan/git/marpa/target/debug/build/libmarpa-sys-a3b1a49cf64d4b2b/out" "--disable-shared" "--enable-static"
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for gawk... (cached) gawk
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking for inline... inline
checking for size_t... yes
checking whether GCC handles -Wextra... -Wextra
checking whether GCC handles -Wdeclaration-after-statement... -Wdeclaration-after-statement
checking size of int... 4
checking for memset... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating LIB_VERSION
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
running: "make" "install"
CDPATH="${ZSH_VERSION+.}:" && cd /home/deyan/git/marpa/libmarpa-sys/libmarpa-8.3.0 && /bin/bash /home/deyan/git/marpa/libmarpa-sys/libmarpa-8.3.0/missing aclocal-1.15 -I m4

--- stderr
/home/deyan/git/marpa/libmarpa-sys/libmarpa-8.3.0/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile:432: /home/deyan/git/marpa/libmarpa-sys/libmarpa-8.3.0/aclocal.m4] Error 127
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/deyan/.cargo/registry/src/github.com-1ecc6299db9ec823/autotools-0.1.3/src/lib.rs:357:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:353
   7: autotools::fail
             at /home/deyan/.cargo/registry/src/github.com-1ecc6299db9ec823/autotools-0.1.3/src/lib.rs:357
   8: autotools::run
             at /home/deyan/.cargo/registry/src/github.com-1ecc6299db9ec823/autotools-0.1.3/src/lib.rs:345
   9: autotools::Config::build
             at /home/deyan/.cargo/registry/src/github.com-1ecc6299db9ec823/autotools-0.1.3/src/lib.rs:321
  10: build_script_build::main
             at libmarpa-sys/build.rs:11
  11: std::rt::lang_start::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  15: std::rt::lang_start
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```

**Comment by dginev** [comment]
Really looks as an issue with the updated `libmarpa-sys` crate rather than this one.

**Comment by dginev** [comment]
For what it's worth, the last building commit for me is at c3acea648dcb2cee6a35e1560d8ed34bb55c1aff 

Starting with 4d20f05c072b2b9ee2412f61accad10613c30108 I am observing this type of build errors.

Debugging further, my machine has a `/usr/bin/aclocal-1.16`, while the build is trying to execute a 1.15 executable, and fails. Trying to untangle why there is a version mismatch...
